# Generated by Django 4.2.1 on 2023-06-09 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(db_column='patient_id', primary_key=True, serialize=False)),
                ('patient_name', models.CharField(db_column='patient_name', max_length=15)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
        migrations.CreateModel(
            name='MedicalAppointment',
            fields=[
                ('medical_appointment_id', models.AutoField(db_column='medical_appointment_id', primary_key=True, serialize=False)),
                ('appointment_datetime', models.DateTimeField(db_column='appointment_datetime')),
                ('expiration_datetime', models.DateTimeField(db_column='expiration_datetime')),
                ('status', models.IntegerField(db_column='status', default=0)),
                ('doctor_id', models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('patient_id', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='appointments.patient')),
            ],
            options={
                'db_table': 'medical_appointment',
            },
        ),
    ]
